local map = vim.keymap.set

map("n", "<leader>e", "<cmd>Neotree toggle<cr>", { silent = true })

map("n", "<C-h>", "<C-w>h", { silent = true })
map("n", "<C-l>", "<C-w>l", { silent = true })
map("n", "<C-j>", "<C-w>j", { silent = true })
map("n", "<C-k>", "<C-w>k", { silent = true })

map("n", "<D-h>", "<C-w>h", { silent = true })
map("n", "<D-l>", "<C-w>l", { silent = true })
map("n", "<D-j>", "<C-w>j", { silent = true })
map("n", "<D-k>", "<C-w>k", { silent = true })

map("n", "<leader>v", "<C-w>v", { silent = true })
map("n", "<leader>h", "<C-w>s", { silent = true })
map("n", "<D-o>", "<C-w>r", { silent = true })

map("n", "<leader>x", "<cmd>close<cr>", { silent = true })
map("n", "<leader>w", "<cmd>w<cr>", { silent = true })

map("n", "<leader>bp", "<cmd>BufferLineTogglePin<cr>", { silent = true })
map("n", "<leader>bq", "<cmd>BufferLineCloseOther<cr>", { silent = true })

map("n", "<leader>ff", "<cmd>Telescope find_files<cr>", { silent = true })
map("n", "<leader>fd", vim.diagnostic.open_float, { silent = true })
map("n", "<leader>fg", "<cmd>Telescope live_grep<cr>", { silent = true })
map("n", "<leader>ft", "<cmd>TodoTelescope<cr>", { silent = true })
map("n", "<leader>fr", "<cmd>Telescope oldfiles<cr>", { silent = true })
map("n", "<leader><leader>", "<cmd>Telescope builtin<cr>", { silent = true })

map("n", "<leader>ot", "<cmd>Neotest jump<cr>", { silent = true })
map("n", "<leader>T", "<cmd>Neotest run file<cr>", { silent = true })

map("i", "<C-Space>", "<C-x><C-o>")
map("i", "<C-@>", "<C-x><C-o>")

map("n", "gd", vim.lsp.buf.declaration, { silent = true })
map("n", "gr", "<cmd>Telescope lsp_references<cr>", { silent = true })
map("n", "gD", vim.lsp.buf.type_definition, { silent = true })
map("n", "gi", vim.lsp.buf.implementation, { silent = true })
map("n", "<BS>", "<C-o>", { silent = true })

map("n", "<leader>rr", vim.lsp.buf.rename, { silent = true })

map("n", "<leader>oc", function()
  vim.lsp.buf.format({ async = true })
end, { silent = true })
map("n", "<leader>oi", function()
  vim.lsp.buf.format({ async = true })
end, { silent = true })
map("n", "<leader>oa", function()
  vim.lsp.buf.format({ async = true })
end, { silent = true })

map("n", "<leader>k", vim.lsp.buf.hover, { silent = true })
map("n", "<leader>i", vim.lsp.buf.signature_help, { silent = true })
map("n", "<leader>u", "<cmd>Telescope lsp_references<cr>", { silent = true })

map({ "i", "n" }, "<C-s>", function()
  vim.lsp.buf.signature_help()
end, { silent = true })

map("n", "<leader>a", vim.lsp.buf.code_action, { silent = true })

map("n", "<leader>0", "<cmd>Telescope lsp_document_symbols<cr>", { silent = true })

map({ "n", "x", "o" }, "й", "q")
map({ "n", "x", "o" }, "ц", "w")
map({ "n", "x", "o" }, "у", "e")
map({ "n", "x", "o" }, "к", "r")
map({ "n", "x", "o" }, "е", "t")
map({ "n", "x", "o" }, "н", "y")
map({ "n", "x", "o" }, "г", "u")
map({ "n", "x", "o" }, "ш", "i")
map({ "n", "x", "o" }, "щ", "o")
map({ "n", "x", "o" }, "з", "p")
map({ "n", "x", "o" }, "х", "[")
map({ "n", "x", "o" }, "ъ", "]")

map({ "n", "x", "o" }, "Й", "Q")
map({ "n", "x", "o" }, "Ц", "W")
map({ "n", "x", "o" }, "У", "E")
map({ "n", "x", "o" }, "К", "R")
map({ "n", "x", "o" }, "Е", "T")
map({ "n", "x", "o" }, "Н", "Y")
map({ "n", "x", "o" }, "Г", "U")
map({ "n", "x", "o" }, "Ш", "I")
map({ "n", "x", "o" }, "Щ", "O")
map({ "n", "x", "o" }, "З", "P")
map({ "n", "x", "o" }, "Х", "{")
map({ "n", "x", "o" }, "Ъ", "}")

map({ "n", "x", "o" }, "ф", "a")
map({ "n", "x", "o" }, "ы", "s")
map({ "n", "x", "o" }, "в", "d")
map({ "n", "x", "o" }, "а", "f")
map({ "n", "x", "o" }, "п", "g")
map({ "n", "x", "o" }, "р", "h")
map({ "n", "x", "o" }, "о", "j")
map({ "n", "x", "o" }, "л", "k")
map({ "n", "x", "o" }, "д", "l")
map({ "n", "x", "o" }, "ж", ";")
map({ "n", "x", "o" }, "э", "'")

map({ "n", "x", "o" }, "Ф", "A")
map({ "n", "x", "o" }, "Ы", "S")
map({ "n", "x", "o" }, "В", "D")
map({ "n", "x", "o" }, "А", "F")
map({ "n", "x", "o" }, "П", "G")
map({ "n", "x", "o" }, "Р", "H")
map({ "n", "x", "o" }, "О", "J")
map({ "n", "x", "o" }, "Л", "K")
map({ "n", "x", "o" }, "Д", "L")
map({ "n", "x", "o" }, "Ж", ":")
map({ "n", "x", "o" }, "Э", '"')

map({ "n", "x", "o" }, "я", "z")
map({ "n", "x", "o" }, "ч", "x")
map({ "n", "x", "o" }, "с", "c")
map({ "n", "x", "o" }, "м", "v")
map({ "n", "x", "o" }, "и", "b")
map({ "n", "x", "o" }, "т", "n")
map({ "n", "x", "o" }, "ь", "m")
map({ "n", "x", "o" }, "б", ",")
map({ "n", "x", "o" }, "ю", ".")

map({ "n", "x", "o" }, "Я", "Z")
map({ "n", "x", "o" }, "Ч", "X")
map({ "n", "x", "o" }, "С", "C")
map({ "n", "x", "o" }, "М", "V")
map({ "n", "x", "o" }, "И", "B")
map({ "n", "x", "o" }, "Т", "N")
map({ "n", "x", "o" }, "Ь", "M")
map({ "n", "x", "o" }, "Б", "<")
map({ "n", "x", "o" }, "Ю", ">")

-- vimrc

map("n", "U", "<C-r>", { noremap = true, silent = true })

map("n", "<M-h>", "20h", { noremap = true, silent = true })
map("n", "<M-j>", "10j", { noremap = true, silent = true })
map("n", "<M-k>", "10k", { noremap = true, silent = true })
map("n", "<M-l>", "20l", { noremap = true, silent = true })

map("n", "H", "20h", { noremap = true, silent = true })
map("n", "J", "10j", { noremap = true, silent = true })
map("n", "K", "10k", { noremap = true, silent = true })
map("n", "L", "20l", { noremap = true, silent = true })

map({ "n", "v" }, "d", '"_d', { noremap = true, silent = true })
map({ "n", "v" }, "D", '"_D', { noremap = true, silent = true })
map("n", "x", '"_x', { noremap = true, silent = true })
map("n", "X", '"_X', { noremap = true, silent = true })
map({ "n", "v" }, "c", '"_c', { noremap = true, silent = true })
map({ "n", "v" }, "C", '"_C', { noremap = true, silent = true })

map({ "n", "v" }, "<Tab>", "<cmd>tabnext<cr>", { noremap = true, silent = true })
map({ "n", "v" }, "<S-Tab>", "<cmd>tabprevious<cr>", { noremap = true, silent = true })
